server:
  port: 8086

spring:
  application:
    name: notification-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/notification}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456@}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    # Real google's service and its port
    host: smtp.gmail.com
    port: 587
    username: "huyeunhan@gmail.com"   # Real email username
    password: "czqp bsfs oqzx lovx"   # App password for avoiding abuse

    # Attach username and password when using gmail's service
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    # Encode email's content

  thymeleaf:
    cache: false