server:
  port: 8085

momo:
  partnerCode: ${MOMO_PARTNER_CODE}
  accessKey: ${MOMO_ACCESS_KEY}
  secretKey: ${MOMO_SECRET_KEY}
  endpoint: ${MOMO_ENDPOINT:https://test-payment.momo.vn/v2/gateway/api/create}
  query: ${MOMO_QUERY:https://test-payment.momo.vn/v2/gateway/api/query}
  redirectUrl: ${MOMO_REDIRECT_URL:http://localhost:8085/api/payment/redirect}
  ipnUrl: ${MOMO_IPN_URL:http://localhost:8085/api/payment/ipn}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/clinic_payment}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never
