server:
  port: 8084
spring:
  application:
    name: appointment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/appointment}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456@}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
external-services:
  patient-service:
    base-url: ${PATIENT_SERVICE_BASE_URL:http://localhost:8083}
  doctor-service:
    base-url: ${DOCTOR_SERVICE_BASE_URL:http://localhost:8082}
  notification-service:
    base-url: ${NOTIFICATION_SERVICE_BASE_URL:http://localhost:8086}
services:
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}
appointment-service:
  cancellation-cutoff-hours: ${APPOINTMENT_CANCELLATION_CUTOFF_HOURS:24}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus # Access via /actuator/*
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: appointment-service
    distribution:
      percentiles-histogram:
        http.server.requests: true
